### ISSUE TITLE
Print remove the first 2 charactersfrom String

### ISSUE THREAD

**Issue by benjamin-albrecht** [MastersOfDesaster/Vongpiler#46]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 3 Fibonacci:
Executed command: PSW
Stack: [bonacci: ]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
word: bonacci: Executed command: PRT
Stack: []
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 0 0
Decoded command to: PSA 0
Executed command: PSA
Stack: [0]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
address: 0 -> zal: 610.0Executed command: PRT
Stack: []
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 3  +
Executed command: PSW
Stack: [ ]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
word:  Executed command: PRT
Stack: []
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 0 1
Decoded command to: PSA 1
Executed command: PSA
Stack: [1]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
address: 1 -> zal: 987.0Executed command: PRT
Stack: []
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 3  =
Executed command: PSW
Stack: [ ]
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 17
Decoded command to: PRT
word:  Executed command: PRT
Stack: []
Registers: [0 -> 610.0, 1 -> 987.0, 2 -> 1597.0, 3 -> yup]
Read raw command: 0 2
Decoded command to: PSA 2
Executed command: PSA
Stack: [2]

**Comment by fspiekermann** [comment]
#50 fixed this issue
